name: examapp
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  injectable:  
  percent_indicator: ^4.2.2
  get_it:  
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  retrofit: ^4.6.0
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  bloc:
  flutter_bloc: ^9.1.1
  pretty_dio_logger:
  shared_preferences:
  pinput:
  pin_code_fields: ^8.0.1
  dartz: ^0.10.1
  connectivity_plus: ^5.0.2
  google_fonts: ^6.1.0
  mockito: ^5.4.6
  equatable: ^2.0.7
  skeletonizer: ^2.1.0+1
  shimmer: ^3.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:  
  json_serializable:
  retrofit_generator:
  
  build_runner:  
  
  flutter_lints: ^5.0.0
  test: ^1.25.15




flutter:
  
  generate: true

  
  uses-material-design: true


  assets:
   - lib/core/assets/

  